version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: escape-string-regexp
    versions:
    - 5.0.0
  - dependency-name: terminal-link
    versions:
    - 3.0.0
  - dependency-name: puppeteer
    versions:
    - 8.0.0
